/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SnowPile1Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SnowPile1AddonDeed();
			}
		}

		[ Constructable ]
		public SnowPile1Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 6077 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6085 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6086 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6087 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6088 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6089 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6090 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6091 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6092 );
			AddComponent( ac, 1, 0, 0 );

		}

		public SnowPile1Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SnowPile1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SnowPile1Addon();
			}
		}

		[Constructable]
		public SnowPile1AddonDeed()
		{
			Name = "SnowPile1";
		}

		public SnowPile1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}