
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ChamprampupAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4077, 1, 1, 10}, {4076, 0, 1, 10}, {4073, -1, 1, 10}// 5	6	7	
			, {4078, 1, 0, 10}, {4074, 0, 0, 10}, {4070, -1, 0, 10}// 8	9	10	
			, {4075, 1, -1, 10}, {4072, 0, -1, 10}, {4071, -1, -1, 10}// 11	12	13	
			, {3026, 0, 0, 25}// 64	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ChamprampupAddonDeed();
			}
		}

		[ Constructable ]
		public ChamprampupAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6228, 1, -1, 10, 0, 2, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6228, -1, -1, 10, 0, 2, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6228, -2, -2, 10, 38, 2, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 7960, 0, 0, 10, 0, -1, "Idol of the Champion", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1884, 2, -2, 5, 1106, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1883, -2, 2, 5, 1106, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1882, 2, 2, 5, 1106, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1881, -2, -2, 5, 1106, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1876, -2, 1, 5, 1106, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1875, 1, -2, 5, 1106, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1874, 2, 1, 5, 1106, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1873, 1, 2, 5, 1106, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1876, -2, 0, 5, 1106, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1875, 0, -2, 5, 1106, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1874, 2, 0, 5, 1106, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1873, 0, 2, 5, 1106, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1876, -2, -1, 5, 1106, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1875, -1, -2, 5, 1106, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1874, 2, -1, 5, 1106, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1873, -1, 2, 5, 1106, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1872, 1, 1, 5, 1106, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1872, 1, 0, 5, 1106, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1872, 1, -1, 5, 1106, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1872, 0, 1, 5, 1106, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1872, 0, 0, 5, 1106, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1872, 0, -1, 5, 1106, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1872, -1, 1, 5, 1106, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1872, -1, 0, 5, 1106, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1872, -1, -1, 5, 1106, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1872, 2, 2, 0, 1106, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1872, 2, 1, 0, 1106, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1872, 2, 0, 0, 1106, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1872, 2, -1, 0, 1106, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1872, 2, -2, 0, 1106, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1872, 1, 2, 0, 1106, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1872, 1, 1, 0, 1106, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 1872, 1, 0, 0, 1106, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1872, 1, -1, 0, 1106, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 1872, 1, -2, 0, 1106, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1872, 0, 2, 0, 1106, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1872, 0, 1, 0, 1106, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1872, 0, 0, 0, 1106, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1872, 0, -1, 0, 1106, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1872, 0, -2, 0, 1106, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 1872, -1, 2, 0, 1106, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 1872, -1, 1, 0, 1106, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 1872, -1, 0, 0, 1106, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1872, -1, -1, 0, 1106, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1872, -1, -2, 0, 1106, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 1872, -2, 2, 0, 1106, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1872, -2, 1, 0, 1106, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1872, -2, 0, 0, 1106, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1872, -2, -1, 0, 1106, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1872, -2, -2, 0, 1106, -1, "", 1);// 63

		}

		public ChamprampupAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ChamprampupAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ChamprampupAddon();
			}
		}

		[Constructable]
		public ChamprampupAddonDeed()
		{
			Name = "Champrampup";
		}

		public ChamprampupAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}