
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NexusAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {19323, 0, 1, 0}, {19316, 1, 1, 0}, {19322, 0, -1, 0}// 1	2	3	
			, {19317, -1, 2, 0}, {19318, 0, 2, 0}, {19319, 1, 2, 0}// 4	5	6	
			, {19320, 2, 2, 0}, {19321, 2, 1, 0}, {19324, -1, 1, 0}// 7	8	9	
			, {19325, 1, 0, 0}, {19326, 0, 0, 0}, {19327, 1, -1, 0}// 10	11	12	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new NexusDeed();
			}
		}

		[ Constructable ]
		public NexusAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public NexusAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class NexusDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new NexusAddon();
			}
		}

		[Constructable]
		public NexusDeed()
		{
			Name = "Nexus Deed";
		}

		public NexusDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}